version: "3.8"

services:
  nextjs-app:
    container_name: nextjs-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${PORT}:${PORT}"
    environment:
      - NODE_ENV=production
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    restart: always
